# Generated by Django 4.0.8 on 2022-11-14 15:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_alter_event_host_attendee'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together={('user', 'event')},
        ),
    ]
