FROM public.ecr.aws/docker/library/node:lts-alpine
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock ./
RUN yarn install

COPY . .

EXPOSE 3000

ENV PORT 3000

CMD ["npm", "run", "dev"]