"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from os import getenv
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pd5!s0xp0237d=%3(v#+%0wh!&*l#949+%696v!e(_l)h1yiuo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

STAGE = 'base'

CSRF_COOKIE_HTTPONLY = True
ALLOWED_HOSTS = [
  'localhost',
  "127.0.0.1",
  "23.131.24.126",
  "23.131.24.126:3002",
  "23.131.24.126:8000"
]
CSRF_TRUSTED_ORIGINS = [
  "http://localhost",
  "http://127.0.0.1",
  "http://localhost:3000",
  "http://localhost:3002",
  "http://127.0.0.1:3000",
  "http://127.0.0.1:3002",
  "http://23.131.24.126:3000",
  "http://23.131.24.126:3002",
  "http://23.131.24.126",
  "http://23.131.24.126:8000"
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

DOMAIN = SITE_NAME = getenv('WEB_DOMAIN')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'djangocms_admin_style', # must be before admin
    'users', # must be before auth

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'django_otp',
    'django_otp.plugins.otp_email',

    'django_extensions',
    'captcha',
    'corsheaders',

    # Health Checks
    'health_check',
    'health_check.db',
    # 'health_check.cache',
    'health_check.storage',
    # 'health_check.contrib.migrations',

    # DRF
    'channels',
    'rest_framework',
    'rest_framework.authtoken',
    'djoser',
    'django_filters',
    'drf_recaptcha',

    # Django CMS
    'djangocms_text_ckeditor',
    'djangocms_file',
    'filer',
    'easy_thumbnails',
    'mptt',
    'sekizai',
    'cms',
    'menus',
    'treebeard',

    # Custom Apps
    'sports',
    'events',
    'chat'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    # 'cms.middleware.user.CurrentUserMiddleware',
    # 'cms.middleware.page.CurrentPageMiddleware',
    # 'cms.middleware.toolbar.ToolbarMiddleware',
    # 'cms.middleware.language.LanguageCookieMiddleware'
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['config/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sekizai.context_processors.sekizai',
                'cms.context_processors.cms_settings',
            ],
        },
    },
]

CMS_TEMPLATES = [
    ('base.html', 'Base page template'),
]

WSGI_APPLICATION = 'config.wsgi.application'

SITE_ID = 1
X_FRAME_OPTIONS = 'SAMEORIGIN'

ASGI_APPLICATION = 'config.asgi.application'

CHANNEL_LAYERS = {
  'default': {
    'BACKEND': 'channels_redis.core.RedisChannelLayer',
    'CONFIG': {
        'hosts': [('127.0.0.1', 6379)],
    },
  }
}

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'solatrix',
        'USER': 'root',
        'PASSWORD': 'secret',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AUTH_USER_MODEL = 'users.User'

DJOSER = {
    'PASSWORD_RESET_CONFIRM_URL': 'create-new-password/?uid={uid}&token={token}',
    'USERNAME_RESET_CONFIRM_URL': 'reset-username/?uid={uid}&token={token}',
    'ACTIVATION_URL': 'activate/?uid={uid}&token={token}',
    'SEND_ACTIVATION_EMAIL': True,
    'LOGIN_FIELD': 'email',
    'SERIALIZERS': {
        'current_user': 'users.serializers.FullUserSerializer',
        'token': 'users.serializers.TokenPlusUserSerializer',
        'password_reset': 'users.serializers.PasswordResetWithRecaptcha',
        'token_create': 'users.serializers.LoginWithRecaptcha',
        'user_create': 'users.serializers.SignupWithRecaptcha'
    },
    'EMAIL': {
        'activation': 'users.email.CustomActivationEmail',
        'password_reset': 'users.email.CustomPasswordResetEmail',
    }
}

DRF_RECAPTCHA_SECRET_KEY = RECAPTCHA_PRIVATE_KEY = "6Lfe0qokAAAAALsydZUSZO5-x6--4dJZPVLbxew6"
RECAPTCHA_PUBLIC_KEY = '6Lfe0qokAAAAAEH9yTZnbUbKetdlrfLywvRCSFkQ'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework.authentication.TokenAuthentication',),
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',)
}

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ('en-us', 'English')
]

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_TZ = True

USE_L10N = False

TIME_INPUT_FORMATS = [
    '%I:%M:%S %p',  # 6:22:44 PM
    '%I:%M %p',  # 6:22 PM
    '%I %p',  # 6 PM
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = "/app/static"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

FIXTURE_DIRS = [
    'config/fixtures'
]

APPEND_SLASH = False

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
