# Generated by Django 4.0.8 on 2023-09-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_remove_stadium_latitude_remove_stadium_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='sports_data_season',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
    ]
