# Generated by Django 4.0.8 on 2023-11-02 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_remove_stadium_slug_league_sports_data_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sports.sport'),
        ),
    ]
