# Generated by Django 4.0.8 on 2025-01-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_stadium_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='icon_name',
            field=models.CharField(default='soccer', max_length=100),
            preserve_default=False,
        ),
    ]
