# Generated by Django 4.0.8 on 2023-09-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_stadium_latitude_stadium_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stadium',
            old_name='area',
            new_name='country',
        ),
    ]
