# Generated by Django 4.0.8 on 2025-01-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_alter_league_sport_alter_team_league_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
