# Generated by Django 4.0.8 on 2023-09-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_rename_area_stadium_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
