# Generated by Django 4.0.8 on 2023-09-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0007_alter_stadium_address_alter_stadium_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadium',
            name='slug',
        ),
        migrations.AlterField(
            model_name='stadium',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
