# Generated by Django 4.0.8 on 2022-11-13 05:22

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_about_user_city_user_profile_image_user_state_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.HybridUserManager()),
            ],
        ),
    ]
