# Generated by Django 4.0.8 on 2023-02-15 19:50

import config.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=config.models.LowercaseEmailField(max_length=254, unique=True),
        ),
    ]
