# Generated by Django 4.0.8 on 2022-11-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
