# Generated by Django 4.0.8 on 2023-09-14 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_remove_stadium_slug_league_sports_data_id_and_more'),
        ('events', '0008_alter_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sport',
        ),
        migrations.AddField(
            model_name='event',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sports.round'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
