# Generated by Django 4.0.8 on 2023-09-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_event_end_time_remove_event_sport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
