# Generated by Django 4.0.8 on 2024-09-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_event_end_time_remove_event_sport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ivs_stage_arn',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
