# Generated by Django 4.0.8 on 2024-09-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_ivs_stage_arn'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='ivs_participant_token',
            field=models.TextField(blank=True),
        ),
    ]
