# Generated by Django 4.0.8 on 2025-01-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_attendee_ivs_participant_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='away_team_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='home_team_score',
            field=models.IntegerField(default=0),
        ),
    ]
