# Generated by Django 4.0.8 on 2025-01-10 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_alter_league_sport_alter_team_league_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0012_event_away_team_score_event_home_team_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='chosen_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fans', to='sports.team'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='away_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_events', to='sports.team'),
        ),
        migrations.AlterField(
            model_name='event',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_events', to='sports.team'),
        ),
        migrations.AlterField(
            model_name='event',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sports.round'),
        ),
        migrations.AlterField(
            model_name='event',
            name='stadium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sports.stadium'),
        ),
    ]
